# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/sda4";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "commit=120" "autodefrag" "subvol=nixos" ];
    };

  fileSystems."/home" =
    { device = "/dev/sda4";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "commit=120" "autodefrag" "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/sda4";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "commit=120" "autodefrag" "subvol=nix" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/sda4";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "commit=120" "autodefrag" "subvol=docker" ];
    };

  fileSystems."/var/lib/libvirt/images" =
    { device = "/dev/sda4";
      fsType = "btrfs";
      options = [ "compress-force=zstd:1" "noatime" "commit=120" "autodefrag" "subvol=images" ];
    };

  fileSystems."/data" =
    { device = "/dev/sdb1";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C3F0-7A24";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/438b8347-67df-4c1e-97f2-4f2268f35907"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
